# Generated by Django 4.0.3 on 2022-03-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
